### ISSUE TITLE
Find out how to read .md files and render it on website

### ISSUE THREAD

**Issue by JoeNg93** [JoeNg93/vtqh-blog#32]
https://www.gatsbyjs.com/plugins/gatsby-source-filesystem/
https://www.gatsbyjs.com/plugins/gatsby-transformer-remark/

**Comment by duyanh3110** [comment]
https://www.gatsbyjs.com/docs/how-to/routing/adding-markdown-pages/
https://www.gatsbyjs.com/docs/how-to/routing/adding-markdown-pages/#frontmatter-for-metadata-in-markdown-files
